name = "ReinforcementLearningEnvironmentClassicControl"
uuid = "1ddd4a80-adb3-11e8-0ef3-afb88dac13d5"
authors = ["Johanni Brea <jbrea@users.noreply.github.com>", "Jun Tian <tianjun.cpp@gmail.com>"]
version = "0.1.0"

[deps]
GR = "28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71"
ReinforcementLearningBase = "e575027e-6cd6-5018-9292-cdc6200d2b44"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
